//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MeyawoPortfolio.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblEducation
    {
        public int EducationID { get; set; }
        public string Title1 { get; set; }
        public string Title2 { get; set; }
        public string GNO { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
    }
}
